# Form implementation generated from reading ui file 'Code.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Code(object):
    def setupUi(self, Code):
        Code.setObjectName("Code")
        Code.resize(600, 750)
        self.widget_2 = QtWidgets.QWidget(parent=Code)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 880, 800))
        self.widget_2.setMinimumSize(QtCore.QSize(880, 800))
        self.widget_2.setMaximumSize(QtCore.QSize(880, 800))
        self.widget_2.setSizeIncrement(QtCore.QSize(880, 800))
        self.widget_2.setStyleSheet("background: #1f8ddb")
        self.widget_2.setObjectName("widget_2")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(210, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.code_button = QtWidgets.QPushButton(parent=self.widget_2)
        self.code_button.setGeometry(QtCore.QRect(50, 660, 500, 75))
        self.code_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.code_button.setObjectName("code_button")
        self.code = QtWidgets.QTextEdit(parent=self.widget_2)
        self.code.setGeometry(QtCore.QRect(50, 50, 501, 591))
        self.code.setStyleSheet("background: #fcfcf2;   border-radius: 10px;")
        self.code.setObjectName("code")

        self.retranslateUi(Code)
        QtCore.QMetaObject.connectSlotsByName(Code)

    def retranslateUi(self, Code):
        _translate = QtCore.QCoreApplication.translate
        Code.setWindowTitle(_translate("Code", "Code"))
        self.label_7.setText(_translate("Code", "Код на языке Python"))
        self.code_button.setText(_translate("Code", "Выйти"))
