# Form implementation generated from reading ui file 'Data.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Data(object):
    def setupUi(self, Data):
        Data.setObjectName("Data")
        Data.resize(880, 800)
        Data.setMinimumSize(QtCore.QSize(880, 800))
        Data.setMaximumSize(QtCore.QSize(880, 800))
        self.widget_2 = QtWidgets.QWidget(parent=Data)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 880, 800))
        self.widget_2.setMinimumSize(QtCore.QSize(880, 800))
        self.widget_2.setMaximumSize(QtCore.QSize(880, 800))
        self.widget_2.setSizeIncrement(QtCore.QSize(880, 800))
        self.widget_2.setStyleSheet("background: #1f8ddb")
        self.widget_2.setObjectName("widget_2")
        self.table_data = QtWidgets.QTableWidget(parent=self.widget_2)
        self.table_data.setGeometry(QtCore.QRect(10, 450, 861, 341))
        self.table_data.setStyleSheet("background: #fcfcf2;   border-radius: 10px;")
        self.table_data.setObjectName("table_data")
        self.table_data.setColumnCount(0)
        self.table_data.setRowCount(0)
        self.table = QtWidgets.QComboBox(parent=self.widget_2)
        self.table.setGeometry(QtCore.QRect(500, 70, 151, 21))
        self.table.setStyleSheet("background: #fcfcf2;   border-radius: 10px;")
        self.table.setObjectName("table")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(450, 70, 51, 21))
        self.label_6.setObjectName("label_6")
        self.text_up_table = QtWidgets.QLabel(parent=self.widget_2)
        self.text_up_table.setGeometry(QtCore.QRect(370, 420, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.text_up_table.setFont(font)
        self.text_up_table.setObjectName("text_up_table")
        self.clear_sql_button = QtWidgets.QPushButton(parent=self.widget_2)
        self.clear_sql_button.setGeometry(QtCore.QRect(440, 340, 191, 51))
        self.clear_sql_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.clear_sql_button.setObjectName("clear_sql_button")
        self.change_table_button = QtWidgets.QPushButton(parent=self.widget_2)
        self.change_table_button.setGeometry(QtCore.QRect(450, 100, 151, 31))
        self.change_table_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.change_table_button.setObjectName("change_table_button")
        self.search = QtWidgets.QPushButton(parent=self.widget_2)
        self.search.setGeometry(QtCore.QRect(10, 340, 131, 41))
        self.search.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.search.setObjectName("search")
        self.error_filter = QtWidgets.QLabel(parent=self.widget_2)
        self.error_filter.setGeometry(QtCore.QRect(20, 390, 291, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.error_filter.setFont(font)
        self.error_filter.setStyleSheet("color: #f00")
        self.error_filter.setObjectName("error_filter")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setGeometry(QtCore.QRect(530, 40, 121, 20))
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(450, 40, 71, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(130, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.filter_table = QtWidgets.QTableWidget(parent=self.widget_2)
        self.filter_table.setGeometry(QtCore.QRect(10, 40, 421, 291))
        self.filter_table.setStyleSheet("background: #fcfcf2;   border-radius: 10px;")
        self.filter_table.setObjectName("filter_table")
        self.filter_table.setColumnCount(0)
        self.filter_table.setRowCount(0)
        self.clear = QtWidgets.QPushButton(parent=self.widget_2)
        self.clear.setGeometry(QtCore.QRect(150, 340, 131, 41))
        self.clear.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.clear.setObjectName("clear")
        self.text_up_table_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.text_up_table_2.setGeometry(QtCore.QRect(550, 10, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.text_up_table_2.setFont(font)
        self.text_up_table_2.setObjectName("text_up_table_2")
        self.text_up_table_3 = QtWidgets.QLabel(parent=self.widget_2)
        self.text_up_table_3.setGeometry(QtCore.QRect(610, 140, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.text_up_table_3.setFont(font)
        self.text_up_table_3.setObjectName("text_up_table_3")
        self.add_data_button_3 = QtWidgets.QPushButton(parent=self.widget_2)
        self.add_data_button_3.setGeometry(QtCore.QRect(440, 180, 431, 41))
        self.add_data_button_3.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.add_data_button_3.setObjectName("add_data_button_3")
        self.delete_data_button = QtWidgets.QPushButton(parent=self.widget_2)
        self.delete_data_button.setGeometry(QtCore.QRect(440, 290, 431, 41))
        self.delete_data_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.delete_data_button.setObjectName("delete_data_button")
        self.error_add = QtWidgets.QLabel(parent=self.widget_2)
        self.error_add.setGeometry(QtCore.QRect(460, 240, 391, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.error_add.setFont(font)
        self.error_add.setStyleSheet("color: #f00")
        self.error_add.setObjectName("error_add")

        self.retranslateUi(Data)
        QtCore.QMetaObject.connectSlotsByName(Data)

    def retranslateUi(self, Data):
        _translate = QtCore.QCoreApplication.translate
        Data.setWindowTitle(_translate("Data", "Data"))
        self.label_6.setText(_translate("Data", "Таблица:"))
        self.text_up_table.setText(_translate("Data", "Данные таблицы"))
        self.clear_sql_button.setText(_translate("Data", "Сохранить и выйти"))
        self.change_table_button.setText(_translate("Data", "выбрать"))
        self.search.setText(_translate("Data", "Найти"))
        self.error_filter.setText(_translate("Data", "Текст об ошибке"))
        self.label.setText(_translate("Data", "имя базы данных"))
        self.label_9.setText(_translate("Data", "База данных:"))
        self.label_10.setText(_translate("Data", "Поиск по значениям"))
        self.clear.setText(_translate("Data", "Очистить"))
        self.text_up_table_2.setText(_translate("Data", "Управление данными"))
        self.text_up_table_3.setText(_translate("Data", "Данные"))
        self.add_data_button_3.setText(_translate("Data", "Добавить ячейку"))
        self.delete_data_button.setText(_translate("Data", "Удалить выбранные"))
        self.error_add.setText(_translate("Data", "Текст об ошибке"))
