# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1060, 720)
        Main.setMinimumSize(QtCore.QSize(1060, 720))
        Main.setMaximumSize(QtCore.QSize(1060, 720))
        self.centralwidget = QtWidgets.QWidget(parent=Main)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1061, 721))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.VizSQL = QtWidgets.QStackedWidget(parent=self.gridLayoutWidget)
        self.VizSQL.setStyleSheet("b")
        self.VizSQL.setObjectName("VizSQL")
        self.Log_in = QtWidgets.QWidget()
        self.Log_in.setObjectName("Log_in")
        self.widget = QtWidgets.QWidget(parent=self.Log_in)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1059, 721))
        self.widget.setStyleSheet("background: #1f8ddb")
        self.widget.setObjectName("widget")
        self.NAME_text = QtWidgets.QLabel(parent=self.widget)
        self.NAME_text.setGeometry(QtCore.QRect(420, 100, 130, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(28)
        self.NAME_text.setFont(font)
        self.NAME_text.setObjectName("NAME_text")
        self.LOGIN_text = QtWidgets.QLabel(parent=self.widget)
        self.LOGIN_text.setGeometry(QtCore.QRect(240, 250, 75, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LOGIN_text.setFont(font)
        self.LOGIN_text.setObjectName("LOGIN_text")
        self.login = QtWidgets.QLineEdit(parent=self.widget)
        self.login.setGeometry(QtCore.QRect(300, 250, 300, 30))
        self.login.setStyleSheet("background: #fcfcf2;   border-radius: 10px;")
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(parent=self.widget)
        self.password.setGeometry(QtCore.QRect(300, 300, 300, 30))
        self.password.setStyleSheet("background: #fcfcf2;   border-radius: 10px;")
        self.password.setObjectName("password")
        self.PASSWORD_text = QtWidgets.QLabel(parent=self.widget)
        self.PASSWORD_text.setGeometry(QtCore.QRect(225, 300, 75, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.PASSWORD_text.setFont(font)
        self.PASSWORD_text.setObjectName("PASSWORD_text")
        self.log_in_button = QtWidgets.QPushButton(parent=self.widget)
        self.log_in_button.setGeometry(QtCore.QRect(350, 390, 251, 41))
        self.log_in_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.log_in_button.setObjectName("log_in_button")
        self.newuser_button_2 = QtWidgets.QPushButton(parent=self.widget)
        self.newuser_button_2.setGeometry(QtCore.QRect(350, 440, 251, 41))
        self.newuser_button_2.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.newuser_button_2.setObjectName("newuser_button_2")
        self.error_Log_in_text = QtWidgets.QLabel(parent=self.widget)
        self.error_Log_in_text.setEnabled(True)
        self.error_Log_in_text.setGeometry(QtCore.QRect(220, 340, 781, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.error_Log_in_text.setFont(font)
        self.error_Log_in_text.setStyleSheet("color: #f00")
        self.error_Log_in_text.setObjectName("error_Log_in_text")
        self.VizSQL.addWidget(self.Log_in)
        self.Registration = QtWidgets.QWidget()
        self.Registration.setObjectName("Registration")
        self.widget_4 = QtWidgets.QWidget(parent=self.Registration)
        self.widget_4.setGeometry(QtCore.QRect(0, -1, 1200, 771))
        self.widget_4.setStyleSheet("background: #1f8ddb")
        self.widget_4.setObjectName("widget_4")
        self.NAME_text_4 = QtWidgets.QLabel(parent=self.widget_4)
        self.NAME_text_4.setGeometry(QtCore.QRect(420, 100, 130, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(28)
        self.NAME_text_4.setFont(font)
        self.NAME_text_4.setObjectName("NAME_text_4")
        self.LOGIN_text_4 = QtWidgets.QLabel(parent=self.widget_4)
        self.LOGIN_text_4.setGeometry(QtCore.QRect(240, 300, 75, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LOGIN_text_4.setFont(font)
        self.LOGIN_text_4.setObjectName("LOGIN_text_4")
        self.PASSWORD_text_3 = QtWidgets.QLabel(parent=self.widget_4)
        self.PASSWORD_text_3.setGeometry(QtCore.QRect(225, 350, 75, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.PASSWORD_text_3.setFont(font)
        self.PASSWORD_text_3.setObjectName("PASSWORD_text_3")
        self.CHECK = QtWidgets.QCheckBox(parent=self.widget_4)
        self.CHECK.setGeometry(QtCore.QRect(230, 410, 231, 41))
        self.CHECK.setObjectName("CHECK")
        self.NAMEUSER_text_ = QtWidgets.QLabel(parent=self.widget_4)
        self.NAMEUSER_text_.setGeometry(QtCore.QRect(260, 250, 75, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.NAMEUSER_text_.setFont(font)
        self.NAMEUSER_text_.setObjectName("NAMEUSER_text_")
        self.newuser_password_2 = QtWidgets.QLineEdit(parent=self.widget_4)
        self.newuser_password_2.setGeometry(QtCore.QRect(300, 350, 300, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newuser_password_2.sizePolicy().hasHeightForWidth())
        self.newuser_password_2.setSizePolicy(sizePolicy)
        self.newuser_password_2.setStyleSheet("background: #fcfcf2;   border-radius: 10px;\n"
"input[type=password] {\n"
"  background: yellow;\n"
"}")
        self.newuser_password_2.setObjectName("newuser_password_2")
        self.newuser_name = QtWidgets.QLineEdit(parent=self.widget_4)
        self.newuser_name.setGeometry(QtCore.QRect(300, 250, 300, 30))
        self.newuser_name.setStyleSheet("background: #fcfcf2;   border-radius: 10px;")
        self.newuser_name.setObjectName("newuser_name")
        self.newuser_login = QtWidgets.QLineEdit(parent=self.widget_4)
        self.newuser_login.setGeometry(QtCore.QRect(300, 300, 300, 30))
        self.newuser_login.setStyleSheet("background: #fcfcf2;   border-radius: 10px;")
        self.newuser_login.setObjectName("newuser_login")
        self.return_log_in_button = QtWidgets.QPushButton(parent=self.widget_4)
        self.return_log_in_button.setGeometry(QtCore.QRect(430, 480, 151, 51))
        self.return_log_in_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.return_log_in_button.setObjectName("return_log_in_button")
        self.newuser_error_text = QtWidgets.QLabel(parent=self.widget_4)
        self.newuser_error_text.setGeometry(QtCore.QRect(390, 410, 301, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.newuser_error_text.setFont(font)
        self.newuser_error_text.setStyleSheet("color: #f00")
        self.newuser_error_text.setText("")
        self.newuser_error_text.setObjectName("newuser_error_text")
        self.newuser_button_3 = QtWidgets.QPushButton(parent=self.widget_4)
        self.newuser_button_3.setGeometry(QtCore.QRect(220, 480, 201, 51))
        self.newuser_button_3.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.newuser_button_3.setObjectName("newuser_button_3")
        self.VizSQL.addWidget(self.Registration)
        self.main_menu = QtWidgets.QWidget()
        self.main_menu.setObjectName("main_menu")
        self.up_menu = QtWidgets.QWidget(parent=self.main_menu)
        self.up_menu.setGeometry(QtCore.QRect(0, 0, 211, 390))
        self.up_menu.setStyleSheet("background: #1f8ddb;  border: 2px;")
        self.up_menu.setObjectName("up_menu")
        self.createtable_button = QtWidgets.QPushButton(parent=self.up_menu)
        self.createtable_button.setGeometry(QtCore.QRect(5, 180, 191, 31))
        self.createtable_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.createtable_button.setObjectName("createtable_button")
        self.createdatabase_button = QtWidgets.QPushButton(parent=self.up_menu)
        self.createdatabase_button.setGeometry(QtCore.QRect(5, 93, 191, 31))
        self.createdatabase_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.createdatabase_button.setObjectName("createdatabase_button")
        self.mydatabase_button = QtWidgets.QPushButton(parent=self.up_menu)
        self.mydatabase_button.setGeometry(QtCore.QRect(5, 60, 191, 30))
        self.mydatabase_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.mydatabase_button.setObjectName("mydatabase_button")
        self.label_2 = QtWidgets.QLabel(parent=self.up_menu)
        self.label_2.setGeometry(QtCore.QRect(60, 33, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.up_menu)
        self.label_3.setGeometry(QtCore.QRect(45, 10, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(parent=self.up_menu)
        self.label_10.setGeometry(QtCore.QRect(70, 160, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.datatable_button = QtWidgets.QPushButton(parent=self.up_menu)
        self.datatable_button.setGeometry(QtCore.QRect(5, 213, 191, 31))
        self.datatable_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.datatable_button.setObjectName("datatable_button")
        self.label_6 = QtWidgets.QLabel(parent=self.up_menu)
        self.label_6.setGeometry(QtCore.QRect(80, 280, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.code_button = QtWidgets.QPushButton(parent=self.up_menu)
        self.code_button.setGeometry(QtCore.QRect(5, 333, 191, 31))
        self.code_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.code_button.setObjectName("code_button")
        self.deletedatabase_button_2 = QtWidgets.QPushButton(parent=self.up_menu)
        self.deletedatabase_button_2.setGeometry(QtCore.QRect(5, 246, 191, 31))
        self.deletedatabase_button_2.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.deletedatabase_button_2.setObjectName("deletedatabase_button_2")
        self.deletedatabase_button = QtWidgets.QPushButton(parent=self.up_menu)
        self.deletedatabase_button.setGeometry(QtCore.QRect(5, 126, 191, 31))
        self.deletedatabase_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.deletedatabase_button.setObjectName("deletedatabase_button")
        self.save_database = QtWidgets.QPushButton(parent=self.up_menu)
        self.save_database.setGeometry(QtCore.QRect(5, 300, 191, 31))
        self.save_database.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.save_database.setObjectName("save_database")
        self.widget_2 = QtWidgets.QWidget(parent=self.main_menu)
        self.widget_2.setGeometry(QtCore.QRect(310, 0, 751, 71))
        self.widget_2.setStyleSheet("background: #1f8ddb")
        self.widget_2.setObjectName("widget_2")
        self.Log_out_button = QtWidgets.QPushButton(parent=self.widget_2)
        self.Log_out_button.setGeometry(QtCore.QRect(670, 20, 70, 40))
        self.Log_out_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #000;\n"
"    border-radius: 10px;\n"
"    background: #f00;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #f2f2ed;\n"
"    }")
        self.Log_out_button.setObjectName("Log_out_button")
        self.profile_button = QtWidgets.QPushButton(parent=self.widget_2)
        self.profile_button.setGeometry(QtCore.QRect(600, 20, 70, 40))
        self.profile_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.profile_button.setObjectName("profile_button")
        self.download_button = QtWidgets.QPushButton(parent=self.widget_2)
        self.download_button.setGeometry(QtCore.QRect(10, 20, 71, 41))
        self.download_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.download_button.setObjectName("download_button")
        self.widget_3 = QtWidgets.QWidget(parent=self.main_menu)
        self.widget_3.setGeometry(QtCore.QRect(210, -1, 101, 391))
        self.widget_3.setStyleSheet("background: #1f8ddb")
        self.widget_3.setObjectName("widget_3")
        self.add_table_image_button = QtWidgets.QPushButton(parent=self.widget_3)
        self.add_table_image_button.setGeometry(QtCore.QRect(10, 170, 30, 30))
        self.add_table_image_button.setText("")
        self.add_table_image_button.setIconSize(QtCore.QSize(25, 25))
        self.add_table_image_button.setObjectName("add_table_image_button")
        self.delete_database_image_button = QtWidgets.QPushButton(parent=self.widget_3)
        self.delete_database_image_button.setGeometry(QtCore.QRect(50, 100, 30, 30))
        self.delete_database_image_button.setText("")
        self.delete_database_image_button.setIconSize(QtCore.QSize(25, 25))
        self.delete_database_image_button.setObjectName("delete_database_image_button")
        self.add_database_image_button = QtWidgets.QPushButton(parent=self.widget_3)
        self.add_database_image_button.setGeometry(QtCore.QRect(10, 100, 30, 30))
        self.add_database_image_button.setText("")
        self.add_database_image_button.setIconSize(QtCore.QSize(25, 25))
        self.add_database_image_button.setObjectName("add_database_image_button")
        self.label_13 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_28 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_28.setGeometry(QtCore.QRect(10, 70, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_29.setGeometry(QtCore.QRect(20, 140, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.delete_table_image_buttonm = QtWidgets.QPushButton(parent=self.widget_3)
        self.delete_table_image_buttonm.setGeometry(QtCore.QRect(50, 170, 30, 30))
        self.delete_table_image_buttonm.setText("")
        self.delete_table_image_buttonm.setIconSize(QtCore.QSize(25, 25))
        self.delete_table_image_buttonm.setObjectName("delete_table_image_buttonm")
        self.label_30 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_30.setGeometry(QtCore.QRect(20, 210, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.profile_image_button = QtWidgets.QPushButton(parent=self.widget_3)
        self.profile_image_button.setGeometry(QtCore.QRect(10, 240, 30, 30))
        self.profile_image_button.setText("")
        self.profile_image_button.setIconSize(QtCore.QSize(25, 25))
        self.profile_image_button.setObjectName("profile_image_button")
        self.save_database_image_button = QtWidgets.QPushButton(parent=self.widget_3)
        self.save_database_image_button.setGeometry(QtCore.QRect(50, 240, 30, 30))
        self.save_database_image_button.setText("")
        self.save_database_image_button.setIconSize(QtCore.QSize(25, 25))
        self.save_database_image_button.setObjectName("save_database_image_button")
        self.log_out_image_button = QtWidgets.QPushButton(parent=self.widget_3)
        self.log_out_image_button.setGeometry(QtCore.QRect(50, 280, 30, 30))
        self.log_out_image_button.setText("")
        self.log_out_image_button.setIconSize(QtCore.QSize(25, 25))
        self.log_out_image_button.setObjectName("log_out_image_button")
        self.code_image_button = QtWidgets.QPushButton(parent=self.widget_3)
        self.code_image_button.setGeometry(QtCore.QRect(10, 280, 30, 30))
        self.code_image_button.setText("")
        self.code_image_button.setIconSize(QtCore.QSize(25, 25))
        self.code_image_button.setObjectName("code_image_button")
        self.down_menu = QtWidgets.QStackedWidget(parent=self.main_menu)
        self.down_menu.setGeometry(QtCore.QRect(0, 390, 311, 331))
        self.down_menu.setStyleSheet("background: #1f8ddb")
        self.down_menu.setObjectName("down_menu")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.down_menu.addWidget(self.page)
        self.database_change = QtWidgets.QWidget()
        self.database_change.setObjectName("database_change")
        self.label_8 = QtWidgets.QLabel(parent=self.database_change)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(parent=self.database_change)
        self.label_5.setGeometry(QtCore.QRect(50, 0, 151, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.save_change_database_button = QtWidgets.QPushButton(parent=self.database_change)
        self.save_change_database_button.setGeometry(QtCore.QRect(10, 270, 281, 41))
        self.save_change_database_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.save_change_database_button.setObjectName("save_change_database_button")
        self.label_31 = QtWidgets.QLabel(parent=self.database_change)
        self.label_31.setGeometry(QtCore.QRect(10, 80, 161, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: #f00")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(parent=self.database_change)
        self.label_32.setGeometry(QtCore.QRect(10, 110, 271, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: #f00")
        self.label_32.setObjectName("label_32")
        self.my_data_base_change = QtWidgets.QComboBox(parent=self.database_change)
        self.my_data_base_change.setGeometry(QtCore.QRect(90, 40, 171, 21))
        self.my_data_base_change.setStyleSheet("background: #fcfcf2;   border-radius: 10px;")
        self.my_data_base_change.setObjectName("my_data_base_change")
        self.change_check_database = QtWidgets.QCheckBox(parent=self.database_change)
        self.change_check_database.setGeometry(QtCore.QRect(10, 150, 161, 20))
        self.change_check_database.setObjectName("change_check_database")
        self.down_menu.addWidget(self.database_change)
        self.delete_table = QtWidgets.QWidget()
        self.delete_table.setObjectName("delete_table")
        self.label_14 = QtWidgets.QLabel(parent=self.delete_table)
        self.label_14.setGeometry(QtCore.QRect(80, 20, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.delete_table)
        self.label_15.setGeometry(QtCore.QRect(10, 70, 121, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.delete_table)
        self.label_16.setGeometry(QtCore.QRect(10, 110, 231, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: #f00")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.delete_table)
        self.label_17.setGeometry(QtCore.QRect(10, 150, 201, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: #f00")
        self.label_17.setObjectName("label_17")
        self.delete_check_database = QtWidgets.QCheckBox(parent=self.delete_table)
        self.delete_check_database.setGeometry(QtCore.QRect(10, 190, 161, 20))
        self.delete_check_database.setObjectName("delete_check_database")
        self.delete_button_button_save = QtWidgets.QPushButton(parent=self.delete_table)
        self.delete_button_button_save.setGeometry(QtCore.QRect(80, 230, 191, 31))
        self.delete_button_button_save.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.delete_button_button_save.setObjectName("delete_button_button_save")
        self.my_data_base_change_2 = QtWidgets.QComboBox(parent=self.delete_table)
        self.my_data_base_change_2.setGeometry(QtCore.QRect(145, 76, 150, 21))
        self.my_data_base_change_2.setStyleSheet("background: #fcfcf2;   border-radius: 10px;")
        self.my_data_base_change_2.setObjectName("my_data_base_change_2")
        self.error_delete_database = QtWidgets.QLabel(parent=self.delete_table)
        self.error_delete_database.setGeometry(QtCore.QRect(40, 280, 201, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.error_delete_database.setFont(font)
        self.error_delete_database.setStyleSheet("color: #f00")
        self.error_delete_database.setObjectName("error_delete_database")
        self.down_menu.addWidget(self.delete_table)
        self.create_database = QtWidgets.QWidget()
        self.create_database.setObjectName("create_database")
        self.save_new_database_button = QtWidgets.QPushButton(parent=self.create_database)
        self.save_new_database_button.setGeometry(QtCore.QRect(90, 190, 181, 31))
        self.save_new_database_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.save_new_database_button.setObjectName("save_new_database_button")
        self.label_4 = QtWidgets.QLabel(parent=self.create_database)
        self.label_4.setGeometry(QtCore.QRect(50, 0, 151, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.name_new_database = QtWidgets.QLineEdit(parent=self.create_database)
        self.name_new_database.setGeometry(QtCore.QRect(82, 50, 121, 21))
        self.name_new_database.setStyleSheet("background: #fcfcf2;   border-radius: 10px")
        self.name_new_database.setObjectName("name_new_database")
        self.check_new_database = QtWidgets.QCheckBox(parent=self.create_database)
        self.check_new_database.setGeometry(QtCore.QRect(10, 140, 171, 31))
        self.check_new_database.setObjectName("check_new_database")
        self.label_7 = QtWidgets.QLabel(parent=self.create_database)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 51, 21))
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(parent=self.create_database)
        self.label_11.setGeometry(QtCore.QRect(10, 80, 271, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: #f00")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.create_database)
        self.label_12.setGeometry(QtCore.QRect(10, 110, 271, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: #f00")
        self.label_12.setObjectName("label_12")
        self.error_create_database_text = QtWidgets.QLabel(parent=self.create_database)
        self.error_create_database_text.setGeometry(QtCore.QRect(20, 250, 271, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.error_create_database_text.setFont(font)
        self.error_create_database_text.setStyleSheet("color: #f00")
        self.error_create_database_text.setText("")
        self.error_create_database_text.setObjectName("error_create_database_text")
        self.down_menu.addWidget(self.create_database)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.delete_and_save_table = QtWidgets.QPushButton(parent=self.page_2)
        self.delete_and_save_table.setGeometry(QtCore.QRect(50, 280, 191, 31))
        self.delete_and_save_table.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.delete_and_save_table.setObjectName("delete_and_save_table")
        self.label = QtWidgets.QLabel(parent=self.page_2)
        self.label.setGeometry(QtCore.QRect(90, 10, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_24 = QtWidgets.QLabel(parent=self.page_2)
        self.label_24.setGeometry(QtCore.QRect(10, 100, 121, 31))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(parent=self.page_2)
        self.label_25.setGeometry(QtCore.QRect(10, 240, 171, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: #f00")
        self.label_25.setObjectName("label_25")
        self.PASSWORD_text_7 = QtWidgets.QLabel(parent=self.page_2)
        self.PASSWORD_text_7.setGeometry(QtCore.QRect(10, 60, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PASSWORD_text_7.setFont(font)
        self.PASSWORD_text_7.setObjectName("PASSWORD_text_7")
        self.name_used_database_delete_table = QtWidgets.QLabel(parent=self.page_2)
        self.name_used_database_delete_table.setGeometry(QtCore.QRect(110, 60, 211, 31))
        self.name_used_database_delete_table.setObjectName("name_used_database_delete_table")
        self.delete_check = QtWidgets.QCheckBox(parent=self.page_2)
        self.delete_check.setGeometry(QtCore.QRect(10, 210, 161, 20))
        self.delete_check.setObjectName("delete_check")
        self.label_26 = QtWidgets.QLabel(parent=self.page_2)
        self.label_26.setGeometry(QtCore.QRect(10, 170, 201, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: #f00")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(parent=self.page_2)
        self.label_27.setGeometry(QtCore.QRect(10, 130, 231, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: #f00")
        self.label_27.setObjectName("label_27")
        self.table_delete = QtWidgets.QComboBox(parent=self.page_2)
        self.table_delete.setGeometry(QtCore.QRect(125, 105, 101, 21))
        self.table_delete.setStyleSheet("background: #fcfcf2;   border-radius: 10px;")
        self.table_delete.setObjectName("table_delete")
        self.down_menu.addWidget(self.page_2)
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.main_menu)
        self.graphicsView.setGeometry(QtCore.QRect(310, 70, 751, 651))
        self.graphicsView.setStyleSheet("background: #096396; border: 2px solid #0f4266;;")
        self.graphicsView.setObjectName("graphicsView")
        self.VizSQL.addWidget(self.main_menu)
        self.gridLayout.addWidget(self.VizSQL, 0, 0, 1, 1)
        Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main)
        self.VizSQL.setCurrentIndex(2)
        self.down_menu.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MainWindow"))
        self.NAME_text.setText(_translate("Main", "VizSQL"))
        self.LOGIN_text.setText(_translate("Main", "Логин:"))
        self.PASSWORD_text.setText(_translate("Main", "Пароль:"))
        self.log_in_button.setText(_translate("Main", "Войти"))
        self.newuser_button_2.setText(_translate("Main", "Зарегистрироватся"))
        self.error_Log_in_text.setText(_translate("Main", "Пользователь не найден"))
        self.NAME_text_4.setText(_translate("Main", "VizSQL"))
        self.LOGIN_text_4.setText(_translate("Main", "Логин:"))
        self.PASSWORD_text_3.setText(_translate("Main", "Пароль:"))
        self.CHECK.setText(_translate("Main", "Нажмите на квадратик"))
        self.NAMEUSER_text_.setText(_translate("Main", "Имя:"))
        self.return_log_in_button.setText(_translate("Main", "Назад"))
        self.newuser_button_3.setText(_translate("Main", "Зарегистрироваться"))
        self.createtable_button.setText(_translate("Main", "Создать Таблицу"))
        self.createdatabase_button.setText(_translate("Main", "Создать Базу Данных"))
        self.mydatabase_button.setText(_translate("Main", "Мои Базы Данных"))
        self.label_2.setText(_translate("Main", "Базы данных"))
        self.label_3.setText(_translate("Main", "Панель управления"))
        self.label_10.setText(_translate("Main", "Таблицы"))
        self.datatable_button.setText(_translate("Main", "Данные"))
        self.label_6.setText(_translate("Main", "Прочее"))
        self.code_button.setText(_translate("Main", "Код"))
        self.deletedatabase_button_2.setText(_translate("Main", "Удалить таблицу"))
        self.deletedatabase_button.setText(_translate("Main", "Удалить  Базу Данных"))
        self.save_database.setText(_translate("Main", "Сохранить как"))
        self.Log_out_button.setText(_translate("Main", "Выход"))
        self.profile_button.setText(_translate("Main", "Профиль"))
        self.download_button.setText(_translate("Main", "Загрузить"))
        self.label_13.setText(_translate("Main", "Инструменты"))
        self.label_28.setText(_translate("Main", "Базы данных"))
        self.label_29.setText(_translate("Main", "Таблицы"))
        self.label_30.setText(_translate("Main", "Прочее"))
        self.label_8.setText(_translate("Main", "База данных"))
        self.label_5.setText(_translate("Main", "Выберете базу данных:"))
        self.save_change_database_button.setText(_translate("Main", "Сохранить выбор"))
        self.label_31.setText(_translate("Main", "При выборе базы данных "))
        self.label_32.setText(_translate("Main", "Вы автоматически начинаете с ней работать"))
        self.change_check_database.setText(_translate("Main", "ознакомлен с условиями"))
        self.label_14.setText(_translate("Main", "Удаление базы данных"))
        self.label_15.setText(_translate("Main", "Выберете базу данных:"))
        self.label_16.setText(_translate("Main", "Вы больше не сможете использовать"))
        self.label_17.setText(_translate("Main", "Выбранную вами базу данных"))
        self.delete_check_database.setText(_translate("Main", "ознакомлен с условиями"))
        self.delete_button_button_save.setText(_translate("Main", "Удалить"))
        self.error_delete_database.setText(_translate("Main", "Выбранную вами базу данных"))
        self.save_new_database_button.setText(_translate("Main", "Сохранить"))
        self.label_4.setText(_translate("Main", "Создание базы данных"))
        self.check_new_database.setText(_translate("Main", "Ознокомлен с условиями"))
        self.label_7.setText(_translate("Main", "Название:"))
        self.label_11.setText(_translate("Main", "При создании или выборе новой базы данных"))
        self.label_12.setText(_translate("Main", "вы автоматически начинаете работать с ней"))
        self.delete_and_save_table.setText(_translate("Main", "Удалить"))
        self.label.setText(_translate("Main", "Удаление таблицы"))
        self.label_24.setText(_translate("Main", "Выберете таблицу:"))
        self.label_25.setText(_translate("Main", "***Сообщение об ошибке"))
        self.PASSWORD_text_7.setText(_translate("Main", "База данных:"))
        self.name_used_database_delete_table.setText(_translate("Main", "***Название выбранной базы данных"))
        self.delete_check.setText(_translate("Main", "ознакомлен с условиями"))
        self.label_26.setText(_translate("Main", "Выбранную вами таблицу"))
        self.label_27.setText(_translate("Main", "Вы больше не сможете использовать"))
