# Form implementation generated from reading ui file 'Profile.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Profile(object):
    def setupUi(self, Profile):
        Profile.setObjectName("Profile")
        Profile.resize(660, 460)
        Profile.setMaximumSize(QtCore.QSize(660, 460))
        Profile.setSizeIncrement(QtCore.QSize(0, 460))
        self.widget_4 = QtWidgets.QWidget(parent=Profile)
        self.widget_4.setGeometry(QtCore.QRect(0, -2, 861, 621))
        self.widget_4.setStyleSheet("background: #1f8ddb")
        self.widget_4.setObjectName("widget_4")
        self.PASSWORD_text_3 = QtWidgets.QLabel(parent=self.widget_4)
        self.PASSWORD_text_3.setGeometry(QtCore.QRect(290, 20, 101, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PASSWORD_text_3.setFont(font)
        self.PASSWORD_text_3.setObjectName("PASSWORD_text_3")
        self.user_name_profile = QtWidgets.QLineEdit(parent=self.widget_4)
        self.user_name_profile.setGeometry(QtCore.QRect(390, 120, 201, 31))
        self.user_name_profile.setStyleSheet("background: #fcfcf2;   border-radius: 10px;")
        self.user_name_profile.setObjectName("user_name_profile")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(340, 129, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.save_create_pole = QtWidgets.QPushButton(parent=self.widget_4)
        self.save_create_pole.setGeometry(QtCore.QRect(430, 360, 201, 61))
        self.save_create_pole.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.save_create_pole.setObjectName("save_create_pole")
        self.change_image_button = QtWidgets.QPushButton(parent=self.widget_4)
        self.change_image_button.setGeometry(QtCore.QRect(60, 370, 201, 41))
        self.change_image_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #0f4266;\n"
"    border-radius: 10px;\n"
"    background: #227cbd;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: #31c3d6;\n"
"    }")
        self.change_image_button.setObjectName("change_image_button")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_4)
        self.label_5.setGeometry(QtCore.QRect(340, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.name_login_text = QtWidgets.QLabel(parent=self.widget_4)
        self.name_login_text.setGeometry(QtCore.QRect(410, 190, 131, 20))
        self.name_login_text.setObjectName("name_login_text")
        self.name_profile_text = QtWidgets.QLabel(parent=self.widget_4)
        self.name_profile_text.setGeometry(QtCore.QRect(330, 70, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name_profile_text.setFont(font)
        self.name_profile_text.setObjectName("name_profile_text")
        self.profile_image = QtWidgets.QLabel(parent=self.widget_4)
        self.profile_image.setGeometry(QtCore.QRect(40, 80, 250, 250))
        self.profile_image.setStyleSheet("border: 5px solid #000")
        self.profile_image.setText("")
        self.profile_image.setObjectName("profile_image")
        self.label = QtWidgets.QLabel(parent=self.widget_4)
        self.label.setGeometry(QtCore.QRect(110, 40, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Profile)
        QtCore.QMetaObject.connectSlotsByName(Profile)

    def retranslateUi(self, Profile):
        _translate = QtCore.QCoreApplication.translate
        Profile.setWindowTitle(_translate("Profile", "Dialog"))
        self.PASSWORD_text_3.setText(_translate("Profile", "Профиль"))
        self.label_4.setText(_translate("Profile", "Имя:"))
        self.save_create_pole.setText(_translate("Profile", "Сохранить и выйти"))
        self.change_image_button.setText(_translate("Profile", "Изменить фото"))
        self.label_5.setText(_translate("Profile", "Логин:"))
        self.name_login_text.setText(_translate("Profile", "***Неизменный логин"))
        self.name_profile_text.setText(_translate("Profile", "Здравствуйте"))
        self.label.setText(_translate("Profile", "Ваша иконка"))
